### ISSUE TITLE
我这边使用了这个插件，但是提示运行时提示 TypeError: Cannot read property 'permissions' of undefined

### ISSUE THREAD

**Issue by guijiyang** [longting/cordova-plugin-android-permissions-plus#1]
我看了下cordova.plugins.permissions，plugins是没有定义的

**Comment by longting** [comment]
debug可以看到cordova这个对象存在吗？

**Comment by longting** [comment]
plugins未定义，检查你的cordova工程是否有问题，你用的windows环境还是linux，还是mac？

**Comment by guijiyang** [comment]
Linux环境，从打印上看是有定义的，但是我不知道哪里出了问题
`window.console.log(cordova);
      window.console.log(cordova.platformId+cordova.platformVersion);
      window.console.log(cordova.plugins);
      window.console.log(cordova.plugins.permissions);`

打印
`Object
addConstructor:function (func) { … }
addDocumentEventHandler:function (event) { … }
addStickyDocumentEventHandler:function (event) { … }
addWindowEventHandler:function (event) { … }
callbackError:function (callbackId, args) { … }
callbackFromNative:function (callbackId, isSuccess, status, args, keepCallback) { … }
callbackId:321695756
callbacks:Object {CoreAndroid321695754: Object}
callbackStatus:Object {NO_RESULT: 0, OK: 1, CLASS_NOT_FOUND_EXCEPTION: 2, …}
callbackSuccess:function (callbackId, args) { … }
define:function (id, factory) { … }
exec:function androidExec(success, fail, service, action, args) { … }
fireDocumentEvent:function (type, data, bNoDetach) { … }
fireWindowEvent:function (type, data) { … }
getOriginalHandlers:function () { … }
platformId:"android"
platformVersion:"8.0.0"
plugins:Object {permissions: Permissions}
removeDocumentEventHandler:function (event) { … }
removeWindowEventHandler:function (event) { … }
require:function (id) { … }
version:"8.0.0"
__proto__:Object {constructor: , __defineGetter__: , __defineSetter__: , …}

android8.0.0

undefined

执行权限操作失败： TypeError: Cannot read property 'permissions' of undefined`

**Comment by longting** [comment]
我看你打印的cordova对象日志里面显示plugins已经有值了  
`plugins:Object {permissions: Permissions}`    
我用的cordova版本是8.1.2，我看你的是`version:"8.0.0"`
我建议你找下你的cordova工程的环境问题，因为连plugins对象都获取不到。

**Comment by guijiyang** [comment]
恩，是环境问题，莫名奇妙的，我今天重新打开就可以了
